#!/usr/bin/env node
var argv = require('minimist')(process.argv.slice(2));
var open = require('open');
var os = require('os');
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');

var port = argv._[0];
var config = require("./webpack.conf.js").devServer(port);

var compiler = webpack(config);
var server = new WebpackDevServer(compiler, {
  contentBase: './build',
  noInfo: false,
  quiet: false,
  stats: {
    assets: false,
    chunkModules: false,
    chunks: true,
    colors: true,
    hash: false,
    timings: true,
    version: false,
  },
});

server.listen(port);
var url = 'http://' + os.hostname() + ':' + port + '/webpack-dev-server/';
console.log('Server started at:\n', url, '\n');
if (argv.open || argv.o) {
  open(url);
}
